#import <UIKit/UIKit.h>
static NSString *const kKey=@"ChickenLedgerTransactions";
static NSArray *Products(void){return @[@"雞腿",@"雞胸",@"雞翅",@"雞屁股",@"雞脖"];}
static double Total(NSArray *a){double n=0;for(NSDictionary *x in a)n+=[x[@"price"] doubleValue]*[x[@"quantity"] doubleValue];return n;}
static NSString *Money(double n){return [NSString stringWithFormat:@"$ %.0f",n];}
static NSMutableArray *Load(void){NSArray *a=[[NSUserDefaults standardUserDefaults]objectForKey:kKey];return a?[a mutableCopy]:[NSMutableArray array];}
static void Save(NSArray *a){[[NSUserDefaults standardUserDefaults]setObject:a forKey:kKey];[[NSUserDefaults standardUserDefaults]synchronize];}
static UILabel *Label(NSString *s,CGFloat z,UIFontWeight w){UILabel *l=[UILabel new];l.text=s;l.font=[UIFont systemFontOfSize:z weight:w];l.textColor=UIColor.labelColor;l.numberOfLines=0;return l;}
static void CLStyle(UIButton *b,UIColor *bg){b.backgroundColor=bg;[b setTitleColor:UIColor.whiteColor forState:UIControlStateNormal];b.layer.cornerRadius=14;b.titleLabel.font=[UIFont systemFontOfSize:16 weight:UIFontWeightSemibold];}
@interface CLHome:UIViewController
@property(nonatomic,strong)UITextField *place,*price,*qty;@property(nonatomic,strong)UIButton *pick;@property(nonatomic,strong)UILabel *sum,*empty;@property(nonatomic,strong)UIStackView *lines;@property(nonatomic,strong)NSMutableArray *draft;@property(nonatomic,copy)NSString *selected;
@end
@implementation CLHome
- (void)viewDidLoad{[super viewDidLoad];self.title=@"新增銷售";self.view.backgroundColor=UIColor.systemGroupedBackgroundColor;self.draft=[NSMutableArray array];self.selected=Products().firstObject;[self build];[self render];}
- (UITextField *)field:(NSString *)p type:(UIKeyboardType)t{UITextField *f=[UITextField new];f.placeholder=p;f.font=[UIFont systemFontOfSize:17 weight:UIFontWeightMedium];f.textColor=UIColor.labelColor;f.backgroundColor=UIColor.secondarySystemBackgroundColor;f.layer.cornerRadius=12;f.layer.borderWidth=1;f.layer.borderColor=UIColor.separatorColor.CGColor;f.leftView=[[UIView alloc]initWithFrame:CGRectMake(0,0,14,1)];f.leftViewMode=UITextFieldViewModeAlways;f.keyboardType=t;[f.heightAnchor constraintEqualToConstant:50].active=YES;return f;}
- (void)build{UIScrollView *sc=[UIScrollView new];sc.translatesAutoresizingMaskIntoConstraints=NO;[self.view addSubview:sc];[NSLayoutConstraint activateConstraints:@[[sc.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor],[sc.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor],[sc.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor],[sc.bottomAnchor constraintEqualToAnchor:self.view.bottomAnchor]]];UIStackView *root=[[UIStackView alloc]init];root.axis=UILayoutConstraintAxisVertical;root.spacing=16;root.layoutMargins=UIEdgeInsetsMake(22,18,30,18);root.layoutMarginsRelativeArrangement=YES;root.translatesAutoresizingMaskIntoConstraints=NO;[sc addSubview:root];[NSLayoutConstraint activateConstraints:@[[root.topAnchor constraintEqualToAnchor:sc.contentLayoutGuide.topAnchor],[root.leadingAnchor constraintEqualToAnchor:sc.frameLayoutGuide.leadingAnchor],[root.trailingAnchor constraintEqualToAnchor:sc.frameLayoutGuide.trailingAnchor],[root.bottomAnchor constraintEqualToAnchor:sc.contentLayoutGuide.bottomAnchor]]];
[root addArrangedSubview:Label(@"今天賣了多少？",30,UIFontWeightBold)];UILabel *hint=Label(@"逐筆加入銷售，完成後一次結算",15,UIFontWeightRegular);hint.textColor=UIColor.secondaryLabelColor;[root addArrangedSubview:hint];
[root addArrangedSubview:Label(@"銷售地點",13,UIFontWeightSemibold)];self.place=[self field:@"例如：市場 A 攤" type:UIKeyboardTypeDefault];[root addArrangedSubview:self.place];[root addArrangedSubview:Label(@"加入銷售明細",21,UIFontWeightBold)];
self.pick=[UIButton buttonWithType:UIButtonTypeSystem];self.pick.backgroundColor=UIColor.secondarySystemBackgroundColor;self.pick.layer.cornerRadius=14;self.pick.layer.borderWidth=1;self.pick.layer.borderColor=UIColor.separatorColor.CGColor;self.pick.contentHorizontalAlignment=UIControlContentHorizontalAlignmentLeft;[self.pick setTitleColor:UIColor.labelColor forState:UIControlStateNormal];[self.pick setImage:[UIImage systemImageNamed:@"tag.fill"] forState:UIControlStateNormal];[self.pick addTarget:self action:@selector(choose) forControlEvents:UIControlEventTouchUpInside];[root addArrangedSubview:self.pick];[self updatePick];
UIStackView *fs=[[UIStackView alloc]init];fs.axis=UILayoutConstraintAxisHorizontal;fs.spacing=10;self.price=[self field:@"單價" type:UIKeyboardTypeDecimalPad];self.qty=[self field:@"數量" type:UIKeyboardTypeDecimalPad];[fs addArrangedSubview:self.price];[fs addArrangedSubview:self.qty];[self.price.widthAnchor constraintEqualTo:self.qty.widthAnchor].active=YES;[root addArrangedSubview:fs];UIButton *add=[UIButton buttonWithType:UIButtonTypeSystem];[add setTitle:@"＋  加入明細" forState:UIControlStateNormal];[add setImage:[UIImage systemImageNamed:@"plus"] forState:UIControlStateNormal];CLStyle(add,UIColor.systemOrangeColor);[add addTarget:self action:@selector(add) forControlEvents:UIControlEventTouchUpInside];[root addArrangedSubview:add];
[root addArrangedSubview:Label(@"本次明細",21,UIFontWeightBold)];self.lines=[[UIStackView alloc]init];self.lines.axis=UILayoutConstraintAxisVertical;self.lines.spacing=10;[root addArrangedSubview:self.lines];self.empty=Label(@"還沒有加入明細（尚未加入）",15,UIFontWeightRegular);self.empty.textColor=UIColor.tertiaryLabelColor;self.empty.textAlignment=NSTextAlignmentCenter;
UIView *card=[UIView new];card.backgroundColor=UIColor.labelColor;card.layer.cornerRadius=18;UIStackView *cs=[[UIStackView alloc]init];cs.axis=UILayoutConstraintAxisVertical;cs.layoutMargins=UIEdgeInsetsMake(15,18,15,18);cs.layoutMarginsRelativeArrangement=YES;cs.translatesAutoresizingMaskIntoConstraints=NO;[card addSubview:cs];[NSLayoutConstraint activateConstraints:@[[cs.topAnchor constraintEqualToAnchor:card.topAnchor],[cs.leadingAnchor constraintEqualToAnchor:card.leadingAnchor],[cs.trailingAnchor constraintEqualToAnchor:card.trailingAnchor],[cs.bottomAnchor constraintEqualToAnchor:card.bottomAnchor]]];UILabel *cap=Label(@"本次應收",13,UIFontWeightSemibold);cap.textColor=UIColor.secondaryLabelColor;[cs addArrangedSubview:cap];self.sum=Label(@"$ 0",34,UIFontWeightBold);self.sum.textColor=UIColor.systemOrangeColor;[cs addArrangedSubview:self.sum];[root addArrangedSubview:card];UIButton *done=[UIButton buttonWithType:UIButtonTypeSystem];[done setTitle:@"完成結算並儲存" forState:UIControlStateNormal];CLStyle(done,UIColor.systemOrangeColor);[done addTarget:self action:@selector(save) forControlEvents:UIControlEventTouchUpInside];[root addArrangedSubview:done];}
- (void)updatePick{[self.pick setTitle:[NSString stringWithFormat:@"品項：%@   ›",self.selected] forState:UIControlStateNormal];}
- (void)choose{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"選擇品項" message:nil preferredStyle:UIAlertControllerStyleActionSheet];for(NSString *p in Products())[a addAction:[UIAlertAction actionWithTitle:p style:UIAlertActionStyleDefault handler:^(UIAlertAction *x){self.selected=p;[self updatePick];}]];[a addAction:[UIAlertAction actionWithTitle:@"取消" style:UIAlertActionStyleCancel handler:nil]];[self presentViewController:a animated:YES completion:nil];}
- (void)add{double p=self.price.text.doubleValue,q=self.qty.text.doubleValue;if(p<=0||q<=0){[self message:@"請輸入正確的單價和數量"];return;}[self.view endEditing:YES];[self.draft addObject:@{@"name":self.selected,@"price":@(p),@"quantity":@(q)}];self.price.text=@"";self.qty.text=@"";[self render];}
- (void)render{for(UIView *v in [self.lines.arrangedSubviews copy]){[self.lines removeArrangedSubview:v];[v removeFromSuperview];}if(!self.draft.count)[self.lines addArrangedSubview:self.empty];for(NSInteger n=0;n<self.draft.count;n++){NSDictionary *i=self.draft[n];UIView *row=[UIView new];row.backgroundColor=UIColor.secondarySystemBackgroundColor;row.layer.cornerRadius=14;row.layer.borderWidth=1;row.layer.borderColor=UIColor.separatorColor.CGColor;UILabel *l=Label([NSString stringWithFormat:@"%@   %@ × %.0f   =   %@",i[@"name"],Money([i[@"price"]doubleValue]),[i[@"quantity"]doubleValue],Money([i[@"price"]doubleValue]*[i[@"quantity"]doubleValue])],16,UIFontWeightSemibold);l.translatesAutoresizingMaskIntoConstraints=NO;UIButton *del=[UIButton buttonWithType:UIButtonTypeSystem];[del setImage:[UIImage systemImageNamed:@"trash"] forState:UIControlStateNormal];del.tintColor=UIColor.systemRedColor;del.tag=n;del.translatesAutoresizingMaskIntoConstraints=NO;[del addTarget:self action:@selector(remove:) forControlEvents:UIControlEventTouchUpInside];[row addSubview:l];[row addSubview:del];[NSLayoutConstraint activateConstraints:@[[l.topAnchor constraintEqualToAnchor:row.topAnchor constant:14],[l.leadingAnchor constraintEqualToAnchor:row.leadingAnchor constant:14],[l.bottomAnchor constraintEqualToAnchor:row.bottomAnchor constant:-14],[l.trailingAnchor constraintEqualToAnchor:del.leadingAnchor constant:-5],[del.trailingAnchor constraintEqualToAnchor:row.trailingAnchor constant:-10],[del.centerYAnchor constraintEqualToAnchor:row.centerYAnchor],[del.widthAnchor constraintEqualToConstant:36],[del.heightAnchor constraintEqualToConstant:36]]];[self.lines addArrangedSubview:row];}self.sum.text=Money(Total(self.draft));}
- (void)remove:(UIButton *)b{[self.draft removeObjectAtIndex:b.tag];[self render];}
- (void)save{if(!self.draft.count){[self message:@"請先加入至少一筆銷售明細"];return;}NSMutableArray *a=Load();[a insertObject:@{@"date":[self date],@"place":self.place.text.length?self.place.text:@"未填地點",@"items":[self.draft copy]} atIndex:0];Save(a);[self.draft removeAllObjects];[self render];[self message:@"已完成結算，紀錄已儲存"];}
- (NSString *)date{NSDateFormatter *f=[NSDateFormatter new];f.dateFormat=@"yyyy-MM-dd HH:mm";return [f stringFromDate:NSDate.date];}
- (void)message:(NSString *)s{UIAlertController *a=[UIAlertController alertControllerWithTitle:@"雞帳本" message:s preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"好" style:UIAlertActionStyleDefault handler:nil]];[self presentViewController:a animated:YES completion:nil];}
@end
@interface CLHistory:UITableViewController@property(nonatomic,strong)NSMutableArray *data;@end
@implementation CLHistory
- (void)viewDidLoad{[super viewDidLoad];self.title=@"銷售紀錄";self.tableView.backgroundColor=UIColor.systemGroupedBackgroundColor;self.navigationItem.rightBarButtonItem=[[UIBarButtonItem alloc]initWithBarButtonSystemItem:UIBarButtonSystemItemAction target:self action:@selector(exportCSV)];}
- (void)viewWillAppear:(BOOL)x{[super viewWillAppear:x];self.data=Load();[self.tableView reloadData];}
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s{return self.data.count;}
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)p{UITableViewCell *c=[t dequeueReusableCellWithIdentifier:@"c"];if(!c)c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:@"c"];NSDictionary *x=self.data[p.row];c.textLabel.text=[NSString stringWithFormat:@"%@   %@",x[@"place"],Money(Total(x[@"items"]))];c.detailTextLabel.text=[NSString stringWithFormat:@"%@ · %lu 筆明細",x[@"date"],(unsigned long)[x[@"items"]count]];c.accessoryType=UITableViewCellAccessoryDisclosureIndicator;return c;}
- (void)tableView:(UITableView *)t didSelectRowAtIndexPath:(NSIndexPath *)p{NSDictionary *x=self.data[p.row];NSMutableString *m=[NSMutableString stringWithFormat:@"%@",x[@"date"]];for(NSDictionary *i in x[@"items"])[m appendFormat:@" | %@   %@ × %.0f = %@",i[@"name"],Money([i[@"price"]doubleValue]),[i[@"quantity"]doubleValue],Money([i[@"price"]doubleValue]*[i[@"quantity"]doubleValue])];UIAlertController *a=[UIAlertController alertControllerWithTitle:[NSString stringWithFormat:@"%@  %@",x[@"place"],Money(Total(x[@"items"]))] message:m preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"關閉" style:UIAlertActionStyleDefault handler:nil]];[self presentViewController:a animated:YES completion:nil];}
- (void)tableView:(UITableView *)t commitEditingStyle:(UITableViewCellEditingStyle)s forRowAtIndexPath:(NSIndexPath *)p{if(s==UITableViewCellEditingStyleDelete){[self.data removeObjectAtIndex:p.row];Save(self.data);[t deleteRowsAtIndexPaths:@[p] withRowAnimation:UITableViewRowAnimationAutomatic];}}
- (void)exportCSV{NSMutableString *csv=[NSMutableString stringWithString:@"日期,地點,品項,單價,數量,小計 | "];for(NSDictionary *x in self.data)for(NSDictionary *i in x[@"items"])[csv appendFormat:@"%@,%@,%@,%.0f,%.0f,%.0f | ",x[@"date"],x[@"place"],i[@"name"],[i[@"price"]doubleValue],[i[@"quantity"]doubleValue],[i[@"price"]doubleValue]*[i[@"quantity"]doubleValue]];NSURL *u=[NSURL fileURLWithPath:[NSTemporaryDirectory()stringByAppendingPathComponent:@"ChickenLedger.csv"]];[csv writeToURL:u atomically:YES encoding:NSUTF8StringEncoding error:nil];[self presentViewController:[[UIActivityViewController alloc]initWithActivityItems:@[u] applicationActivities:nil] animated:YES completion:nil];}
@end
@interface AppDelegate:UIResponder<UIApplicationDelegate>@property(nonatomic,strong)UIWindow *window;@end
@implementation AppDelegate
- (BOOL)application:(UIApplication *)a didFinishLaunchingWithOptions:(NSDictionary *)o{self.window=[[UIWindow alloc]initWithFrame:UIScreen.mainScreen.bounds];UINavigationBarAppearance *n=[UINavigationBarAppearance new];[n configureWithDefaultBackground];[UINavigationBar appearance].standardAppearance=n;[UINavigationBar appearance].scrollEdgeAppearance=n;UITabBarAppearance *b=[UITabBarAppearance new];[b configureWithDefaultBackground];[UITabBar appearance].standardAppearance=b;[UITabBar appearance].scrollEdgeAppearance=b;UITabBarController *tabs=[UITabBarController new];UINavigationController *h=[[UINavigationController alloc]initWithRootViewController:[CLHome new]];h.tabBarItem=[[UITabBarItem alloc]initWithTitle:@"今日" image:[UIImage systemImageNamed:@"plus.circle.fill"] tag:0];UINavigationController *r=[[UINavigationController alloc]initWithRootViewController:[CLHistory new]];r.tabBarItem=[[UITabBarItem alloc]initWithTitle:@"紀錄" image:[UIImage systemImageNamed:@"clock.arrow.circlepath"] tag:1];tabs.viewControllers=@[h,r];self.window.rootViewController=tabs;[self.window makeKeyAndVisible];return YES;}
@end
int main(int argc,char *argv[]){@autoreleasepool{return UIApplicationMain(argc,argv,nil,NSStringFromClass(AppDelegate.class));}}
